### ISSUE TITLE
gulp tasks broken

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-portal#164]
Noted while trying to build new docker image

```
    at check_dest (/orr-portal/gulpfile.js:139:3)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12)
    at asyncRunner (/orr-portal/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[14:34:12] 'install' errored after 4.16 ms
The command '/bin/sh -c cd /orr-portal/  && npm install  && gulp install --base=/ont/ --dest=/orr-ont/src/main/webapp/' returned a non-zero code: 1
```

**Comment by lewismc** [comment]
I'll take a look

**Comment by carueda** [comment]
I have fixed a few of the broken tasks (in particular, those for development purposes seem to be in good shape), but those for distribution are still broken.
