### ISSUE TITLE
Cannot create requested ontology format

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-portal#98]
Copied (and reformatted) from https://github.com/ESIPFed/cor/issues/33

Reported by @lewismc

> I tried manually uploading some RDF data and encountered the issue below. Is the following URI illegal?
>
> **file:/usr/local/ESIPDroneClusterSoftware/example/morning1.csvAirSpeed(m/s)**

```
org.mmisw.orr.ont.service.CannotCreateFormat: Map(
uri -> http://cor.esipfed.org/ont/~lmcgibbn/morning1, 
version -> 20170412T000427, 
format -> rdf, 
error -> Cannot create requested ontology format: com.hp.hpl.jena.shared.InvalidPropertyURIException: file:/usr/local/ESIPDroneClusterSoftware/example/morning1.csvAirSpeed(m/s)
)
	at org.mmisw.orr.ont.service.OntService.getOntologyFile(OntService.scala:265)
	at org.mmisw.orr.ont.service.TripleStoreServiceAgRest.loadUriFromLocal(TripleStoreServiceAgRest.scala:109)
	at org.mmisw.orr.ont.app.OntController.org$mmisw$orr$ont$app$OntController$$loadOntologyInTripleStore(OntController.scala:634)
	at org.mmisw.orr.ont.app.OntController.org$mmisw$orr$ont$app$OntController$$createOntology(OntController.scala:399)
	at org.mmisw.orr.ont.app.OntController$$anonfun$7.apply(OntController.scala:123)
	at org.mmisw.orr.ont.app.OntController$$anonfun$7.apply(OntController.scala:99)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:270)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178)
	at org.mmisw.orr.ont.app.BaseController.withRouteMultiParams(BaseController.scala:11)
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:264)
	at org.mmisw.orr.ont.app.BaseController.org$scalatra$json$JsonSupport$$super$invoke(BaseController.scala:11)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:74)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:68)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178)
	at org.mmisw.orr.ont.app.BaseController.withRouteMultiParams(BaseController.scala:11)
	at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:68)
	at org.mmisw.orr.ont.app.BaseController.invoke(BaseController.scala:11)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:240)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:238)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:238)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:237)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:493)
	at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:237)
	at org.scalatra.ScalatraServlet.runRoutes(ScalatraServlet.scala:49)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:163)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at org.scalatra.ScalatraServlet.executeRoutes(ScalatraServlet.scala:49)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at org.scalatra.ScalatraServlet.withResponse(ScalatraServlet.scala:49)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at org.scalatra.ScalatraServlet.withRequest(ScalatraServlet.scala:49)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at org.scalatra.ScalatraServlet.withRequestResponse(ScalatraServlet.scala:49)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at org.scalatra.ScalatraServlet.org$scalatra$servlet$ServletBase$$super$handle(ScalatraServlet.scala:49)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at org.mmisw.orr.ont.app.BaseController.org$scalatra$CorsSupport$$super$handle(BaseController.scala:11)
	at org.scalatra.CorsSupport$$anonfun$handle$1.apply$mcV$sp(CORSSupport.scala:202)
	at org.scalatra.CorsSupport$$anonfun$handle$1.apply(CORSSupport.scala:190)
	at org.scalatra.CorsSupport$$anonfun$handle$1.apply(CORSSupport.scala:190)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at org.scalatra.ScalatraServlet.withResponse(ScalatraServlet.scala:49)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at org.scalatra.ScalatraServlet.withRequest(ScalatraServlet.scala:49)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at org.scalatra.ScalatraServlet.withRequestResponse(ScalatraServlet.scala:49)
	at org.scalatra.CorsSupport$class.handle(CORSSupport.scala:188)
	at org.mmisw.orr.ont.app.OntController.org$scalatra$servlet$FileUploadSupport$$super$handle(OntController.scala:24)
	at org.scalatra.servlet.FileUploadSupport$class.handle(FileUploadSupport.scala:93)
	at org.mmisw.orr.ont.app.OntController.handle(OntController.scala:24)
	at org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:54)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by carueda** [comment]
Lewis: Thanks for testing the ORR software (via the COR instance).

Yes, it seems that Jena is complaining about an invalid URI, but I would like to reproduce and confirm. Can you provide a copy of your file?

**Comment by lewismc** [comment]
@carueda see attached file, you will see that it is serialized as Turtle. I've changed the file suffix to .txt to facilitate upload here.
[morning1.txt](https://github.com/mmisw/orr-portal/files/915179/morning1.txt)

**Comment by lewismc** [comment]
This has to do with the use of parentheses within URI's. It looks like this is illegal, however I cannot find concrete evidence of this within the W3C specification(s). I'll keep looking, in the meantime, I've removed the parentheses from the CSV file I was using as the basis for generating the Turtle. This issue can probably be closed @carueda

**Comment by carueda** [comment]
Closed per https://github.com/mmisw/orr-portal/issues/99#issuecomment-293461574
